apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontdep
 namespace: bigapp

spec:
  replicas: 1
  selector:
    matchLabels:
     app: frontapp

  template:
     metadata:
       labels:
          app: frontapp
     spec:
      containers:
       - name: frontpod
         image: trainwithshubham/chatapp-frontend
         ports:
         - containerPort: 80
         env:
         - name: NODE_ENV
           value: production  
        
