kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2
metadata: 
 name: hpascale 
 namespace: bigapp
spec:
 scaleTargetRef:
  kind: Deployment 
  apiVersion: apps/v1
  name: frontdep
 minReplicas: 2
 maxReplicas: 5
 metrics:
  - type: Resource 
    resource: 
     name: memory
     target: 
      type: Utilization
      averageUtilization: 50
     #name: cpu 
     #target : 
      #type: utilization
      #averageUtlization: 50