kind: PersistentVolume
apiVersion: v1
metadata: 
 name: pvolume 
 namespace: bigapp

spec:
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: local-storage
 hostPath: 
  path: /mnt/data  