kind: PersistentVolumeClaim
apiVersion: v1 
metadata: 
 name: mypvc
 namespace: bigapp
spec:
 accessModes:
   - ReadWriteOnce
 resources:
  requests: 
   storage: 1Gi
 storageClassName: local-storage
